# Generated by Django 5.1.1 on 2024-09-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=30)),
                ('created_date', models.DateField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Read_Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read1_path', models.CharField(max_length=255)),
                ('read2_path', models.CharField(max_length=255)),
                ('plate_number', models.IntegerField()),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField()),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sample')),
            ],
        ),
    ]
