# Generated by Django 5.1.1 on 2024-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_label',
            field=models.CharField(default='', max_length=150),
        ),
    ]
